### ISSUE TITLE
Guest User Mode Does Not Work

### ISSUE THREAD

**Issue by noimjosh** [jskidie/Christmas-Community-Groups#1]
The guest user mode does not work after setting GROUPING=true.

Docker logs show the following:
```
Node.js v20.10.0
[ EXPRESS ] Express server started on port 80!
[ DB EXPOSE ] DB has been exposed on port 8080
[ EXPRESS ] ::ffff:192.168.1.135 - GET /wishlist
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error
    at new CustomPouchError (/usr/src/app/node_modules/pouchdb/lib/index.js:656:21)
    at createError (/usr/src/app/node_modules/pouchdb/lib/index.js:665:10)
    at /usr/src/app/node_modules/pouchdb/lib/index.js:5183:25
    at /usr/src/app/node_modules/pouchdb/lib/index.js:4220:9
    at /usr/src/app/node_modules/pouchdb/lib/index.js:4051:13 {
  status: 404,
  name: 'not_found',
  error: true,
  message: 'missing',
  reason: 'missing',
  docId: '_CCUNKNOWN'
}
```

**Comment by noimjosh** [comment]
I just submitted a [Pull Request](https://github.com/jskiddie/Christmas-Community-Groups/pull/2) to allow this feature after testing on my install
